Repository microsoft/vscode-webview-ui-toolkit, pull requests merged in 2021-12, with the labels that each got.

#301 Microsoft security and compliance tasks
  azure-pipelines.yml
Labels: good first issue

#303 Generate SPDX file on build
  azure-pipelines.yml
Labels: enhancement

#308 Add missing type info in component registration functions
  docs/api-report.md
  src/badge/index.ts
  src/button/index.ts
  src/checkbox/index.ts
  src/data-grid/index.ts
  src/divider/index.ts
  src/dropdown/index.ts
  src/link/index.ts
  src/option/index.ts
  src/panels/index.ts
  src/progress-ring/index.ts
  src/radio-group/index.ts
  src/radio/index.ts
  src/tag/index.ts
  src/text-area/index.ts
  src/text-field/index.ts
Labels: bug
